package com.nogeon.economyland.network;

import com.nogeon.economyland.NoGeonEconomyLand;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.network.NetworkRegistry;
import net.minecraftforge.network.simple.SimpleChannel;

public final class ModNetwork {
    private static final String PROTOCOL_VERSION = "1";

    public static final SimpleChannel CHANNEL = NetworkRegistry.newSimpleChannel(
        new ResourceLocation(NoGeonEconomyLand.MOD_ID, "main"),
        () -> PROTOCOL_VERSION,
        PROTOCOL_VERSION::equals,
        PROTOCOL_VERSION::equals
    );

    private ModNetwork() {
    }

    public static void register() {
        int id = 0;
        CHANNEL.registerMessage(
            id++,
            OpenWalletPacket.class,
            OpenWalletPacket::encode,
            OpenWalletPacket::decode,
            OpenWalletPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SpawnReturnPacket.class,
            SpawnReturnPacket::encode,
            SpawnReturnPacket::decode,
            SpawnReturnPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TogglePeacefulFlagPacket.class,
            TogglePeacefulFlagPacket::encode,
            TogglePeacefulFlagPacket::decode,
            TogglePeacefulFlagPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenJobChangePacket.class,
            OpenJobChangePacket::encode,
            OpenJobChangePacket::decode,
            OpenJobChangePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            JobChangePacket.class,
            JobChangePacket::encode,
            JobChangePacket::decode,
            JobChangePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            ToggleItemLockPacket.class,
            ToggleItemLockPacket::encode,
            ToggleItemLockPacket::decode,
            ToggleItemLockPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenSkillsPacket.class,
            OpenSkillsPacket::encode,
            OpenSkillsPacket::decode,
            OpenSkillsPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenHelpPacket.class,
            OpenHelpPacket::encode,
            OpenHelpPacket::decode,
            OpenHelpPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            UpgradeSkillPacket.class,
            UpgradeSkillPacket::encode,
            UpgradeSkillPacket::decode,
            UpgradeSkillPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncCreditsPacket.class,
            SyncCreditsPacket::encode,
            SyncCreditsPacket::decode,
            SyncCreditsPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncPlayerInventoryPacket.class,
            SyncPlayerInventoryPacket::encode,
            SyncPlayerInventoryPacket::decode,
            SyncPlayerInventoryPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncLandSelectionPacket.class,
            SyncLandSelectionPacket::encode,
            SyncLandSelectionPacket::decode,
            SyncLandSelectionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenLandHomePacket.class,
            OpenLandHomePacket::encode,
            OpenLandHomePacket::decode,
            OpenLandHomePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenAdminLandPacket.class,
            OpenAdminLandPacket::encode,
            OpenAdminLandPacket::decode,
            OpenAdminLandPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AdminLandFlagPacket.class,
            AdminLandFlagPacket::encode,
            AdminLandFlagPacket::decode,
            AdminLandFlagPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            HomeActionPacket.class,
            HomeActionPacket::encode,
            HomeActionPacket::decode,
            HomeActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenShopPacket.class,
            OpenShopPacket::encode,
            OpenShopPacket::decode,
            OpenShopPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenAuctionPacket.class,
            OpenAuctionPacket::encode,
            OpenAuctionPacket::decode,
            OpenAuctionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AuctionCreatePacket.class,
            AuctionCreatePacket::encode,
            AuctionCreatePacket::decode,
            AuctionCreatePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AuctionBuyPacket.class,
            AuctionBuyPacket::encode,
            AuctionBuyPacket::decode,
            AuctionBuyPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AuctionCancelPacket.class,
            AuctionCancelPacket::encode,
            AuctionCancelPacket::decode,
            AuctionCancelPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            BuyShopItemPacket.class,
            BuyShopItemPacket::encode,
            BuyShopItemPacket::decode,
            BuyShopItemPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TraderActionPacket.class,
            TraderActionPacket::encode,
            TraderActionPacket::decode,
            TraderActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            LuckExchangePacket.class,
            LuckExchangePacket::encode,
            LuckExchangePacket::decode,
            LuckExchangePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaRollPacket.class,
            GachaRollPacket::encode,
            GachaRollPacket::decode,
            GachaRollPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaCelebratePacket.class,
            GachaCelebratePacket::encode,
            GachaCelebratePacket::decode,
            GachaCelebratePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaClaimStoredPacket.class,
            GachaClaimStoredPacket::encode,
            GachaClaimStoredPacket::decode,
            GachaClaimStoredPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenGachaStoragePacket.class,
            OpenGachaStoragePacket::encode,
            OpenGachaStoragePacket::decode,
            OpenGachaStoragePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaTakeStoredPacket.class,
            GachaTakeStoredPacket::encode,
            GachaTakeStoredPacket::decode,
            GachaTakeStoredPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaRewardSavePacket.class,
            GachaRewardSavePacket::encode,
            GachaRewardSavePacket::decode,
            GachaRewardSavePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaRewardRemovePacket.class,
            GachaRewardRemovePacket::encode,
            GachaRewardRemovePacket::decode,
            GachaRewardRemovePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaRewardResetPacket.class,
            GachaRewardResetPacket::encode,
            GachaRewardResetPacket::decode,
            GachaRewardResetPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaRewardAdminCategoryPacket.class,
            GachaRewardAdminCategoryPacket::encode,
            GachaRewardAdminCategoryPacket::decode,
            GachaRewardAdminCategoryPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            GachaRewardAutoAddPacket.class,
            GachaRewardAutoAddPacket::encode,
            GachaRewardAutoAddPacket::decode,
            GachaRewardAutoAddPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AdminShopAddPacket.class,
            AdminShopAddPacket::encode,
            AdminShopAddPacket::decode,
            AdminShopAddPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AdminShopRemovePacket.class,
            AdminShopRemovePacket::encode,
            AdminShopRemovePacket::decode,
            AdminShopRemovePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AdminShopResetPacket.class,
            AdminShopResetPacket::encode,
            AdminShopResetPacket::decode,
            AdminShopResetPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenTradeBrowserPacket.class,
            OpenTradeBrowserPacket::encode,
            OpenTradeBrowserPacket::decode,
            OpenTradeBrowserPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeRequestPacket.class,
            TradeRequestPacket::encode,
            TradeRequestPacket::decode,
            TradeRequestPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeRespondPacket.class,
            TradeRespondPacket::encode,
            TradeRespondPacket::decode,
            TradeRespondPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeOfferHeldPacket.class,
            TradeOfferHeldPacket::encode,
            TradeOfferHeldPacket::decode,
            TradeOfferHeldPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenTradeItemPacket.class,
            OpenTradeItemPacket::encode,
            OpenTradeItemPacket::decode,
            OpenTradeItemPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeOfferItemPacket.class,
            TradeOfferItemPacket::encode,
            TradeOfferItemPacket::decode,
            TradeOfferItemPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeOfferLandPacket.class,
            TradeOfferLandPacket::encode,
            TradeOfferLandPacket::decode,
            TradeOfferLandPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeSetCreditsPacket.class,
            TradeSetCreditsPacket::encode,
            TradeSetCreditsPacket::decode,
            TradeSetCreditsPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeClearOfferPacket.class,
            TradeClearOfferPacket::encode,
            TradeClearOfferPacket::decode,
            TradeClearOfferPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeChatPacket.class,
            TradeChatPacket::encode,
            TradeChatPacket::decode,
            TradeChatPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            HighLowActionPacket.class,
            HighLowActionPacket::encode,
            HighLowActionPacket::decode,
            HighLowActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SlotMachineActionPacket.class,
            SlotMachineActionPacket::encode,
            SlotMachineActionPacket::decode,
            SlotMachineActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SmithActionPacket.class,
            SmithActionPacket::encode,
            SmithActionPacket::decode,
            SmithActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            DeconstructActionPacket.class,
            DeconstructActionPacket::encode,
            DeconstructActionPacket::decode,
            DeconstructActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeToggleReadyPacket.class,
            TradeToggleReadyPacket::encode,
            TradeToggleReadyPacket::decode,
            TradeToggleReadyPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeConfirmPacket.class,
            TradeConfirmPacket::encode,
            TradeConfirmPacket::decode,
            TradeConfirmPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            TradeCancelPacket.class,
            TradeCancelPacket::encode,
            TradeCancelPacket::decode,
            TradeCancelPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            LandClaimActionPacket.class,
            LandClaimActionPacket::encode,
            LandClaimActionPacket::decode,
            LandClaimActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            LandSelectionClickPacket.class,
            LandSelectionClickPacket::encode,
            LandSelectionClickPacket::decode,
            LandSelectionClickPacket::handle
        );
        CHANNEL.registerMessage(id++, LandPermissionPacket.class, LandPermissionPacket::encode, LandPermissionPacket::decode, LandPermissionPacket::handle);
        CHANNEL.registerMessage(id++, LandFlagPacket.class, LandFlagPacket::encode, LandFlagPacket::decode, LandFlagPacket::handle);
        CHANNEL.registerMessage(id++, LandKickPacket.class, LandKickPacket::encode, LandKickPacket::decode, LandKickPacket::handle);
        CHANNEL.registerMessage(
            id++,
            LandSellPacket.class,
            LandSellPacket::encode,
            LandSellPacket::decode,
            LandSellPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            UpdateMemoPacket.class,
            UpdateMemoPacket::encode,
            UpdateMemoPacket::decode,
            UpdateMemoPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            EnhanceHitVfxPacket.class,
            EnhanceHitVfxPacket::encode,
            EnhanceHitVfxPacket::decode,
            EnhanceHitVfxPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            ReforgeActionPacket.class,
            ReforgeActionPacket::encode,
            ReforgeActionPacket::decode,
            ReforgeActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SocketUpgradeActionPacket.class,
            SocketUpgradeActionPacket::encode,
            SocketUpgradeActionPacket::decode,
            SocketUpgradeActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SocketRemoveGemPacket.class,
            SocketRemoveGemPacket::encode,
            SocketRemoveGemPacket::decode,
            SocketRemoveGemPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            ExtendedInventoryPagePacket.class,
            ExtendedInventoryPagePacket::encode,
            ExtendedInventoryPagePacket::decode,
            ExtendedInventoryPagePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenExtendedInventoryPacket.class,
            OpenExtendedInventoryPacket::encode,
            OpenExtendedInventoryPacket::decode,
            OpenExtendedInventoryPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenCosmeticArmorPacket.class,
            OpenCosmeticArmorPacket::encode,
            OpenCosmeticArmorPacket::decode,
            OpenCosmeticArmorPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            ToggleCosmeticArmorPacket.class,
            ToggleCosmeticArmorPacket::encode,
            ToggleCosmeticArmorPacket::decode,
            ToggleCosmeticArmorPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncCosmeticArmorPacket.class,
            SyncCosmeticArmorPacket::encode,
            SyncCosmeticArmorPacket::decode,
            SyncCosmeticArmorPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            ToggleMinerAbilityPacket.class,
            ToggleMinerAbilityPacket::encode,
            ToggleMinerAbilityPacket::decode,
            ToggleMinerAbilityPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            JobAbilityKeyPacket.class,
            JobAbilityKeyPacket::encode,
            JobAbilityKeyPacket::decode,
            JobAbilityKeyPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            MinerChargePacket.class,
            MinerChargePacket::encode,
            MinerChargePacket::decode,
            MinerChargePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncMinerAbilityPacket.class,
            SyncMinerAbilityPacket::encode,
            SyncMinerAbilityPacket::decode,
            SyncMinerAbilityPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            ToggleHunterSensePacket.class,
            ToggleHunterSensePacket::encode,
            ToggleHunterSensePacket::decode,
            ToggleHunterSensePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            MarkHunterPreyPacket.class,
            MarkHunterPreyPacket::encode,
            MarkHunterPreyPacket::decode,
            MarkHunterPreyPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncHunterAbilityPacket.class,
            SyncHunterAbilityPacket::encode,
            SyncHunterAbilityPacket::decode,
            SyncHunterAbilityPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncFisherDataPacket.class,
            SyncFisherDataPacket::encode,
            SyncFisherDataPacket::decode,
            SyncFisherDataPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SaveCookRecipePacket.class,
            SaveCookRecipePacket::encode,
            SaveCookRecipePacket::decode,
            SaveCookRecipePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            RequestOpenCookRecipePacket.class,
            RequestOpenCookRecipePacket::encode,
            RequestOpenCookRecipePacket::decode,
            RequestOpenCookRecipePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenCookRecipeScreenPacket.class,
            OpenCookRecipeScreenPacket::encode,
            OpenCookRecipeScreenPacket::decode,
            OpenCookRecipeScreenPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            RequestCastBaitPacket.class,
            RequestCastBaitPacket::encode,
            RequestCastBaitPacket::decode,
            RequestCastBaitPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncExtendedInventoryNbtPacket.class,
            SyncExtendedInventoryNbtPacket::encode,
            SyncExtendedInventoryNbtPacket::decode,
            SyncExtendedInventoryNbtPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenCompressionScreenPacket.class,
            OpenCompressionScreenPacket::encode,
            OpenCompressionScreenPacket::decode,
            OpenCompressionScreenPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            CompressionActionPacket.class,
            CompressionActionPacket::encode,
            CompressionActionPacket::decode,
            CompressionActionPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncShopLinesPacket.class,
            SyncShopLinesPacket::encode,
            SyncShopLinesPacket::decode,
            SyncShopLinesPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            PortalTeleportPacket.class,
            PortalTeleportPacket::encode,
            PortalTeleportPacket::decode,
            PortalTeleportPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            OpenAdminCommandPacket.class,
            OpenAdminCommandPacket::encode,
            OpenAdminCommandPacket::decode,
            OpenAdminCommandPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            AdminCommandExecutePacket.class,
            AdminCommandExecutePacket::encode,
            AdminCommandExecutePacket::decode,
            AdminCommandExecutePacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            ResetSkillsPacket.class,
            ResetSkillsPacket::encode,
            ResetSkillsPacket::decode,
            ResetSkillsPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            BuyCartItemsPacket.class,
            BuyCartItemsPacket::encode,
            BuyCartItemsPacket::decode,
            BuyCartItemsPacket::handle
        );
        CHANNEL.registerMessage(
            id++,
            SyncReforgeStatusPacket.class,
            SyncReforgeStatusPacket::encode,
            SyncReforgeStatusPacket::decode,
            SyncReforgeStatusPacket::handle
        );
    }
}
